version: '3'

services:
  mongo:
    container_name: api-gallery-mongo
    image: mongo:latest
    environment: 
      MONGO_INITDB_ROOT_PASSWORD: gallery
      MONGO_INITDB_ROOT_USERNAME: gallery
      MONGO_INITDB_DATABASE: gallery
    ports:
      - 27017:27017

  api:
    container_name: api-gallery
    depends_on: 
      - mongo
    volumes:
      - .:/usr/src/app
    build: 
      context: .
    ports:
      - 3000:8080
    links:
      - mongo:mongo